@echo off
cd /d %~dp0
if "%ELITE_DAYNIGHT_DB%"=="" set ELITE_DAYNIGHT_DB=%cd%\elite_daynight.db
if not exist "%ELITE_DAYNIGHT_DB%" if exist "%cd%\elite_daynight_template.db" copy "%cd%\elite_daynight_template.db" "%ELITE_DAYNIGHT_DB%"
if "%ELITE_API_PORT%"=="" set ELITE_API_PORT=8000
if "%ELITE_DAYNIGHT_AUTOMATION_MODE%"=="" set ELITE_DAYNIGHT_AUTOMATION_MODE=shadow
if "%ELITE_DAYNIGHT_AUTOMATION_BATCH_LIMIT%"=="" set ELITE_DAYNIGHT_AUTOMATION_BATCH_LIMIT=200
if "%ELITE_DAYNIGHT_PARALLEL_EXTENDED_SEARCH%"=="" set ELITE_DAYNIGHT_PARALLEL_EXTENDED_SEARCH=1
if "%ELITE_DAYNIGHT_PREDICTION_WORKERS%"=="" set ELITE_DAYNIGHT_PREDICTION_WORKERS=3
if "%ELITE_DAYNIGHT_PARALLEL_EXTENDED_MIN_HOURS%"=="" set ELITE_DAYNIGHT_PARALLEL_EXTENDED_MIN_HOURS=168
if "%ELITE_DAYNIGHT_PARALLEL_CHUNK_OVERLAP_HOURS%"=="" set ELITE_DAYNIGHT_PARALLEL_CHUNK_OVERLAP_HOURS=2
if "%ELITE_DAYNIGHT_LONG_SEARCH_STEP_SECONDS%"=="" set ELITE_DAYNIGHT_LONG_SEARCH_STEP_SECONDS=300
if "%ELITE_DAYNIGHT_ADAPTIVE_NORMAL_SEARCH%"=="" set ELITE_DAYNIGHT_ADAPTIVE_NORMAL_SEARCH=1
if "%ELITE_DAYNIGHT_NORMAL_SEARCH_MAX_STEP_SECONDS%"=="" set ELITE_DAYNIGHT_NORMAL_SEARCH_MAX_STEP_SECONDS=300
if "%ELITE_DAYNIGHT_NORMAL_SEARCH_MIN_STEP_SECONDS%"=="" set ELITE_DAYNIGHT_NORMAL_SEARCH_MIN_STEP_SECONDS=30
if "%ELITE_DAYNIGHT_NORMAL_SEARCH_EARLY_STOP%"=="" set ELITE_DAYNIGHT_NORMAL_SEARCH_EARLY_STOP=0
if "%ELITE_DAYNIGHT_PARALLEL_FIT%"=="" set ELITE_DAYNIGHT_PARALLEL_FIT=1
if "%ELITE_DAYNIGHT_FIT_WORKERS%"=="" set ELITE_DAYNIGHT_FIT_WORKERS=3
if "%ELITE_DAYNIGHT_FIT_PARALLEL_MIN_COMBOS%"=="" set ELITE_DAYNIGHT_FIT_PARALLEL_MIN_COMBOS=4
if "%ELITE_DAYNIGHT_POI_TRANSITION_CACHE_ENABLED%"=="" set ELITE_DAYNIGHT_POI_TRANSITION_CACHE_ENABLED=1
if "%ELITE_DAYNIGHT_POI_CACHE_NORMAL_LOOKAHEAD_HOURS%"=="" set ELITE_DAYNIGHT_POI_CACHE_NORMAL_LOOKAHEAD_HOURS=72
if "%ELITE_DAYNIGHT_POI_CACHE_PREFETCH_HOURS%"=="" set ELITE_DAYNIGHT_POI_CACHE_PREFETCH_HOURS=24
if "%ELITE_DAYNIGHT_POI_CACHE_PAST_MARGIN_HOURS%"=="" set ELITE_DAYNIGHT_POI_CACHE_PAST_MARGIN_HOURS=1
if "%ELITE_DAYNIGHT_POI_CACHE_REFRESH_MARGIN_HOURS%"=="" set ELITE_DAYNIGHT_POI_CACHE_REFRESH_MARGIN_HOURS=6
if "%ELITE_DAYNIGHT_POI_CACHE_EXTENDED_REFRESH_MARGIN_HOURS%"=="" set ELITE_DAYNIGHT_POI_CACHE_EXTENDED_REFRESH_MARGIN_HOURS=336
if "%ELITE_DAYNIGHT_POI_CACHE_MAX_AGE_HOURS%"=="" set ELITE_DAYNIGHT_POI_CACHE_MAX_AGE_HOURS=24
if "%ELITE_DAYNIGHT_POI_CACHE_MAX_EXTENDED_HOURS%"=="" set ELITE_DAYNIGHT_POI_CACHE_MAX_EXTENDED_HOURS=720
if "%ELITE_DAYNIGHT_POI_CACHE_MAX_CROSSINGS%"=="" set ELITE_DAYNIGHT_POI_CACHE_MAX_CROSSINGS=512
uvicorn elite_daynight_api:app --host 127.0.0.1 --port %ELITE_API_PORT% --workers 1
