#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
export ELITE_DAYNIGHT_DB="${ELITE_DAYNIGHT_DB:-$(pwd)/elite_daynight.db}"
export ELITE_DAYNIGHT_AUTOMATION_MODE="${ELITE_DAYNIGHT_AUTOMATION_MODE:-shadow}"
export ELITE_DAYNIGHT_AUTOMATION_BATCH_LIMIT="${ELITE_DAYNIGHT_AUTOMATION_BATCH_LIMIT:-200}"
export ELITE_DAYNIGHT_PARALLEL_EXTENDED_SEARCH="${ELITE_DAYNIGHT_PARALLEL_EXTENDED_SEARCH:-1}"
export ELITE_DAYNIGHT_PREDICTION_WORKERS="${ELITE_DAYNIGHT_PREDICTION_WORKERS:-3}"
export ELITE_DAYNIGHT_PARALLEL_EXTENDED_MIN_HOURS="${ELITE_DAYNIGHT_PARALLEL_EXTENDED_MIN_HOURS:-168}"
export ELITE_DAYNIGHT_PARALLEL_CHUNK_OVERLAP_HOURS="${ELITE_DAYNIGHT_PARALLEL_CHUNK_OVERLAP_HOURS:-2}"
export ELITE_DAYNIGHT_LONG_SEARCH_STEP_SECONDS="${ELITE_DAYNIGHT_LONG_SEARCH_STEP_SECONDS:-300}"
export ELITE_DAYNIGHT_ADAPTIVE_NORMAL_SEARCH="${ELITE_DAYNIGHT_ADAPTIVE_NORMAL_SEARCH:-1}"
export ELITE_DAYNIGHT_NORMAL_SEARCH_MAX_STEP_SECONDS="${ELITE_DAYNIGHT_NORMAL_SEARCH_MAX_STEP_SECONDS:-300}"
export ELITE_DAYNIGHT_NORMAL_SEARCH_MIN_STEP_SECONDS="${ELITE_DAYNIGHT_NORMAL_SEARCH_MIN_STEP_SECONDS:-30}"
export ELITE_DAYNIGHT_NORMAL_SEARCH_EARLY_STOP="${ELITE_DAYNIGHT_NORMAL_SEARCH_EARLY_STOP:-0}"
export ELITE_DAYNIGHT_PARALLEL_FIT="${ELITE_DAYNIGHT_PARALLEL_FIT:-1}"
export ELITE_DAYNIGHT_FIT_WORKERS="${ELITE_DAYNIGHT_FIT_WORKERS:-3}"
export ELITE_DAYNIGHT_FIT_PARALLEL_MIN_COMBOS="${ELITE_DAYNIGHT_FIT_PARALLEL_MIN_COMBOS:-4}"
if [ ! -f "$ELITE_DAYNIGHT_DB" ] && [ -f "$(pwd)/elite_daynight_template.db" ]; then
  cp "$(pwd)/elite_daynight_template.db" "$ELITE_DAYNIGHT_DB"
fi
exec uvicorn elite_daynight_api:app --host 127.0.0.1 --port "${ELITE_API_PORT:-8000}" --workers 1
